# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Greeting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eGreeting.proto\x12\x08Greeting\"(\n\x08Greeting\x12\r\n\x05\x66Name\x18\x01 \x01(\t\x12\r\n\x05lName\x18\x02 \x01(\t\"7\n\x0fGreetingRequest\x12$\n\x08Greeting\x18\x01 \x01(\x0b\x32\x12.Greeting.Greeting\"\"\n\x10GreetingResponse\x12\x0e\n\x06Result\x18\x01 \x01(\t2S\n\x0fGreetingService\x12@\n\x05Greet\x12\x19.Greeting.GreetingRequest\x1a\x1a.Greeting.GreetingResponse\"\x00\x62\x06proto3')



_GREETING = DESCRIPTOR.message_types_by_name['Greeting']
_GREETINGREQUEST = DESCRIPTOR.message_types_by_name['GreetingRequest']
_GREETINGRESPONSE = DESCRIPTOR.message_types_by_name['GreetingResponse']
Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'Greeting_pb2'
  # @@protoc_insertion_point(class_scope:Greeting.Greeting)
  })
_sym_db.RegisterMessage(Greeting)

GreetingRequest = _reflection.GeneratedProtocolMessageType('GreetingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGREQUEST,
  '__module__' : 'Greeting_pb2'
  # @@protoc_insertion_point(class_scope:Greeting.GreetingRequest)
  })
_sym_db.RegisterMessage(GreetingRequest)

GreetingResponse = _reflection.GeneratedProtocolMessageType('GreetingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGRESPONSE,
  '__module__' : 'Greeting_pb2'
  # @@protoc_insertion_point(class_scope:Greeting.GreetingResponse)
  })
_sym_db.RegisterMessage(GreetingResponse)

_GREETINGSERVICE = DESCRIPTOR.services_by_name['GreetingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETING._serialized_start=28
  _GREETING._serialized_end=68
  _GREETINGREQUEST._serialized_start=70
  _GREETINGREQUEST._serialized_end=125
  _GREETINGRESPONSE._serialized_start=127
  _GREETINGRESPONSE._serialized_end=161
  _GREETINGSERVICE._serialized_start=163
  _GREETINGSERVICE._serialized_end=246
# @@protoc_insertion_point(module_scope)
