# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bImage.proto\x12\x05Image\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x02\n\x05Image\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0e\n\x06Length\x18\x02 \x01(\x03\x12\x15\n\rDirectoryName\x18\x03 \x01(\t\x12\x12\n\nIsReadOnly\x18\x04 \x01(\x08\x12\x10\n\x08IsExists\x18\x05 \x01(\x08\x12\x10\n\x08\x46ullName\x18\x06 \x01(\t\x12\x11\n\tExtension\x18\x07 \x01(\t\x12\x33\n\x0f\x43reationTimeUtc\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x11LastAccessTimeUtc\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10LastWriteTimeUtc\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\nAttributes\x18\x0b \x01(\x0e\x32\x15.Image.FileAttributes\x12\x11\n\tImageBlob\x18\x0c \x01(\x0c\"(\n\tImageList\x12\x1b\n\x05Image\x18\x01 \x03(\x0b\x32\x0c.Image.Image\" \n\x0cImageRequest\x12\x10\n\x08\x46ilePath\x18\x01 \x01(\t\",\n\rImageResponse\x12\x1b\n\x05Image\x18\x01 \x01(\x0b\x32\x0c.Image.Image\")\n\x10ImageListRequest\x12\x15\n\rDirectoryPath\x18\x01 \x01(\t\"8\n\x11ImageListResponse\x12#\n\tImageList\x18\x01 \x01(\x0b\x32\x10.Image.ImageList*\xb5\x02\n\x0e\x46ileAttributes\x12\"\n\x1e\x46irstEnumValueToBeZeroInProto3\x10\x00\x12\x0c\n\x08ReadOnly\x10\x01\x12\n\n\x06Hidden\x10\x02\x12\n\n\x06System\x10\x04\x12\r\n\tDirectory\x10\x10\x12\x0b\n\x07\x41rchive\x10 \x12\n\n\x06\x44\x65vice\x10@\x12\x0b\n\x06Normal\x10\x80\x01\x12\x0e\n\tTemporary\x10\x80\x02\x12\x0f\n\nSparseFile\x10\x80\x04\x12\x11\n\x0cReparsePoint\x10\x80\x08\x12\x0f\n\nCompressed\x10\x80\x10\x12\x0c\n\x07Offline\x10\x80 \x12\x16\n\x11NotContentIndexed\x10\x80@\x12\x0f\n\tEncrypted\x10\x80\x80\x01\x12\x15\n\x0fIntegrityStream\x10\x80\x80\x02\x12\x11\n\x0bNoScrubData\x10\x80\x80\x08\x32\x8c\x01\n\x0cImageService\x12\x37\n\x08GetImage\x12\x13.Image.ImageRequest\x1a\x14.Image.ImageResponse\"\x00\x12\x43\n\x0cGetImageList\x12\x17.Image.ImageListRequest\x1a\x18.Image.ImageListResponse\"\x00\x62\x06proto3')

_FILEATTRIBUTES = DESCRIPTOR.enum_types_by_name['FileAttributes']
FileAttributes = enum_type_wrapper.EnumTypeWrapper(_FILEATTRIBUTES)
FirstEnumValueToBeZeroInProto3 = 0
ReadOnly = 1
Hidden = 2
System = 4
Directory = 16
Archive = 32
Device = 64
Normal = 128
Temporary = 256
SparseFile = 512
ReparsePoint = 1024
Compressed = 2048
Offline = 4096
NotContentIndexed = 8192
Encrypted = 16384
IntegrityStream = 32768
NoScrubData = 131072


_IMAGE = DESCRIPTOR.message_types_by_name['Image']
_IMAGELIST = DESCRIPTOR.message_types_by_name['ImageList']
_IMAGEREQUEST = DESCRIPTOR.message_types_by_name['ImageRequest']
_IMAGERESPONSE = DESCRIPTOR.message_types_by_name['ImageResponse']
_IMAGELISTREQUEST = DESCRIPTOR.message_types_by_name['ImageListRequest']
_IMAGELISTRESPONSE = DESCRIPTOR.message_types_by_name['ImageListResponse']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:Image.Image)
  })
_sym_db.RegisterMessage(Image)

ImageList = _reflection.GeneratedProtocolMessageType('ImageList', (_message.Message,), {
  'DESCRIPTOR' : _IMAGELIST,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:Image.ImageList)
  })
_sym_db.RegisterMessage(ImageList)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:Image.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:Image.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)

ImageListRequest = _reflection.GeneratedProtocolMessageType('ImageListRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGELISTREQUEST,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:Image.ImageListRequest)
  })
_sym_db.RegisterMessage(ImageListRequest)

ImageListResponse = _reflection.GeneratedProtocolMessageType('ImageListResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGELISTRESPONSE,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:Image.ImageListResponse)
  })
_sym_db.RegisterMessage(ImageListResponse)

_IMAGESERVICE = DESCRIPTOR.services_by_name['ImageService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEATTRIBUTES._serialized_start=641
  _FILEATTRIBUTES._serialized_end=950
  _IMAGE._serialized_start=56
  _IMAGE._serialized_end=415
  _IMAGELIST._serialized_start=417
  _IMAGELIST._serialized_end=457
  _IMAGEREQUEST._serialized_start=459
  _IMAGEREQUEST._serialized_end=491
  _IMAGERESPONSE._serialized_start=493
  _IMAGERESPONSE._serialized_end=537
  _IMAGELISTREQUEST._serialized_start=539
  _IMAGELISTREQUEST._serialized_end=580
  _IMAGELISTRESPONSE._serialized_start=582
  _IMAGELISTRESPONSE._serialized_end=638
  _IMAGESERVICE._serialized_start=953
  _IMAGESERVICE._serialized_end=1093
# @@protoc_insertion_point(module_scope)
