import grpc
import os

# Import dependencies generated by gRPC tools
import Image_pb2
import Image_pb2_grpc

MAX_MESSAGE_LENGTH = 500 * 1024 * 1024 #500MB

def serializeToFile(responseImage):
	# Write the new address book back to disk.
	serializeToFileName = str(os.getcwd()+"\\"+responseImage.Image.Name+".dat")
	f = open(serializeToFileName, "wb")
	f.write(responseImage.SerializeToString())
	f.close()
	print("Serialized To File %s" % (serializeToFileName))
	
def getImage(stub):
	responseImage = stub.GetImage(Image_pb2.ImageRequest(FilePath = "D:\\Thamarai\\Research\\Downloads\\coil-100\\coil-100\\obj100__350.png"))
	print("GetImage called %s" % (responseImage.Image.Name))
	serializeToFile(responseImage)

def serializeListToFile(responseImages):
	# Write the new address book back to disk.
	serializeToFileName = str(os.getcwd()+"\\OutputDB.dat")
	f = open(serializeToFileName, "wb")
	f.write(responseImages.SerializeToString())
	f.close()
	print("Serialized To File %s" % (serializeToFileName))
	
def getImageList(stub):
	responseImages = stub.GetImageList(Image_pb2.ImageRequest(FilePath = "D:\\Thamarai\\Research\\Downloads\\coil-100\\coil-100\\"))
	print("GetImageList called")
	serializeListToFile(responseImages)
	
def run():
    # Secured channel using dotnet dev certificate

	with grpc.insecure_channel('localhost:50051', options=[
        ('grpc.max_send_message_length', MAX_MESSAGE_LENGTH),
        ('grpc.max_receive_message_length', MAX_MESSAGE_LENGTH),
    ],) as channel:
		stub = Image_pb2_grpc.ImageServiceStub(channel)

		print("-------------- Get Image --------------")
		getImage(stub)
		print("-------------- Get Image List --------------")
		getImageList(stub)


if __name__ == '__main__':
    run()