// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Image.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Image {

  /// <summary>Holder for reflection information generated from Image.proto</summary>
  public static partial class ImageReflection {

    #region Descriptor
    /// <summary>File descriptor for Image.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ImageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtJbWFnZS5wcm90bxIFSW1hZ2UaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3Rh",
            "bXAucHJvdG8i5wIKBUltYWdlEgwKBE5hbWUYASABKAkSDgoGTGVuZ3RoGAIg",
            "ASgDEhUKDURpcmVjdG9yeU5hbWUYAyABKAkSEgoKSXNSZWFkT25seRgEIAEo",
            "CBIQCghJc0V4aXN0cxgFIAEoCBIQCghGdWxsTmFtZRgGIAEoCRIRCglFeHRl",
            "bnNpb24YByABKAkSMwoPQ3JlYXRpb25UaW1lVXRjGAggASgLMhouZ29vZ2xl",
            "LnByb3RvYnVmLlRpbWVzdGFtcBI1ChFMYXN0QWNjZXNzVGltZVV0YxgJIAEo",
            "CzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASNAoQTGFzdFdyaXRlVGlt",
            "ZVV0YxgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKQoKQXR0",
            "cmlidXRlcxgLIAEoDjIVLkltYWdlLkZpbGVBdHRyaWJ1dGVzEhEKCUltYWdl",
            "QmxvYhgMIAEoDCIoCglJbWFnZUxpc3QSGwoFSW1hZ2UYASADKAsyDC5JbWFn",
            "ZS5JbWFnZSIgCgxJbWFnZVJlcXVlc3QSEAoIRmlsZVBhdGgYASABKAkiLAoN",
            "SW1hZ2VSZXNwb25zZRIbCgVJbWFnZRgBIAEoCzIMLkltYWdlLkltYWdlIikK",
            "EEltYWdlTGlzdFJlcXVlc3QSFQoNRGlyZWN0b3J5UGF0aBgBIAEoCSI4ChFJ",
            "bWFnZUxpc3RSZXNwb25zZRIjCglJbWFnZUxpc3QYASABKAsyEC5JbWFnZS5J",
            "bWFnZUxpc3QqtQIKDkZpbGVBdHRyaWJ1dGVzEiIKHkZpcnN0RW51bVZhbHVl",
            "VG9CZVplcm9JblByb3RvMxAAEgwKCFJlYWRPbmx5EAESCgoGSGlkZGVuEAIS",
            "CgoGU3lzdGVtEAQSDQoJRGlyZWN0b3J5EBASCwoHQXJjaGl2ZRAgEgoKBkRl",
            "dmljZRBAEgsKBk5vcm1hbBCAARIOCglUZW1wb3JhcnkQgAISDwoKU3BhcnNl",
            "RmlsZRCABBIRCgxSZXBhcnNlUG9pbnQQgAgSDwoKQ29tcHJlc3NlZBCAEBIM",
            "CgdPZmZsaW5lEIAgEhYKEU5vdENvbnRlbnRJbmRleGVkEIBAEg8KCUVuY3J5",
            "cHRlZBCAgAESFQoPSW50ZWdyaXR5U3RyZWFtEICAAhIRCgtOb1NjcnViRGF0",
            "YRCAgAgyjAEKDEltYWdlU2VydmljZRI3CghHZXRJbWFnZRITLkltYWdlLklt",
            "YWdlUmVxdWVzdBoULkltYWdlLkltYWdlUmVzcG9uc2UiABJDCgxHZXRJbWFn",
            "ZUxpc3QSFy5JbWFnZS5JbWFnZUxpc3RSZXF1ZXN0GhguSW1hZ2UuSW1hZ2VM",
            "aXN0UmVzcG9uc2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Image.FileAttributes), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.Image), global::Image.Image.Parser, new[]{ "Name", "Length", "DirectoryName", "IsReadOnly", "IsExists", "FullName", "Extension", "CreationTimeUtc", "LastAccessTimeUtc", "LastWriteTimeUtc", "Attributes", "ImageBlob" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.ImageList), global::Image.ImageList.Parser, new[]{ "Image" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.ImageRequest), global::Image.ImageRequest.Parser, new[]{ "FilePath" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.ImageResponse), global::Image.ImageResponse.Parser, new[]{ "Image" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.ImageListRequest), global::Image.ImageListRequest.Parser, new[]{ "DirectoryPath" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Image.ImageListResponse), global::Image.ImageListResponse.Parser, new[]{ "ImageList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum FileAttributes {
    [pbr::OriginalName("FirstEnumValueToBeZeroInProto3")] FirstEnumValueToBeZeroInProto3 = 0,
    [pbr::OriginalName("ReadOnly")] ReadOnly = 1,
    [pbr::OriginalName("Hidden")] Hidden = 2,
    [pbr::OriginalName("System")] System = 4,
    [pbr::OriginalName("Directory")] Directory = 16,
    [pbr::OriginalName("Archive")] Archive = 32,
    [pbr::OriginalName("Device")] Device = 64,
    [pbr::OriginalName("Normal")] Normal = 128,
    [pbr::OriginalName("Temporary")] Temporary = 256,
    [pbr::OriginalName("SparseFile")] SparseFile = 512,
    [pbr::OriginalName("ReparsePoint")] ReparsePoint = 1024,
    [pbr::OriginalName("Compressed")] Compressed = 2048,
    [pbr::OriginalName("Offline")] Offline = 4096,
    [pbr::OriginalName("NotContentIndexed")] NotContentIndexed = 8192,
    [pbr::OriginalName("Encrypted")] Encrypted = 16384,
    [pbr::OriginalName("IntegrityStream")] IntegrityStream = 32768,
    [pbr::OriginalName("NoScrubData")] NoScrubData = 131072,
  }

  #endregion

  #region Messages
  public sealed partial class Image : pb::IMessage<Image>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Image> _parser = new pb::MessageParser<Image>(() => new Image());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Image> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.ImageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Image() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Image(Image other) : this() {
      name_ = other.name_;
      length_ = other.length_;
      directoryName_ = other.directoryName_;
      isReadOnly_ = other.isReadOnly_;
      isExists_ = other.isExists_;
      fullName_ = other.fullName_;
      extension_ = other.extension_;
      creationTimeUtc_ = other.creationTimeUtc_ != null ? other.creationTimeUtc_.Clone() : null;
      lastAccessTimeUtc_ = other.lastAccessTimeUtc_ != null ? other.lastAccessTimeUtc_.Clone() : null;
      lastWriteTimeUtc_ = other.lastWriteTimeUtc_ != null ? other.lastWriteTimeUtc_.Clone() : null;
      attributes_ = other.attributes_;
      imageBlob_ = other.imageBlob_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Image Clone() {
      return new Image(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Length" field.</summary>
    public const int LengthFieldNumber = 2;
    private long length_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    /// <summary>Field number for the "DirectoryName" field.</summary>
    public const int DirectoryNameFieldNumber = 3;
    private string directoryName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DirectoryName {
      get { return directoryName_; }
      set {
        directoryName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IsReadOnly" field.</summary>
    public const int IsReadOnlyFieldNumber = 4;
    private bool isReadOnly_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsReadOnly {
      get { return isReadOnly_; }
      set {
        isReadOnly_ = value;
      }
    }

    /// <summary>Field number for the "IsExists" field.</summary>
    public const int IsExistsFieldNumber = 5;
    private bool isExists_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsExists {
      get { return isExists_; }
      set {
        isExists_ = value;
      }
    }

    /// <summary>Field number for the "FullName" field.</summary>
    public const int FullNameFieldNumber = 6;
    private string fullName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FullName {
      get { return fullName_; }
      set {
        fullName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Extension" field.</summary>
    public const int ExtensionFieldNumber = 7;
    private string extension_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Extension {
      get { return extension_; }
      set {
        extension_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CreationTimeUtc" field.</summary>
    public const int CreationTimeUtcFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp creationTimeUtc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreationTimeUtc {
      get { return creationTimeUtc_; }
      set {
        creationTimeUtc_ = value;
      }
    }

    /// <summary>Field number for the "LastAccessTimeUtc" field.</summary>
    public const int LastAccessTimeUtcFieldNumber = 9;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastAccessTimeUtc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastAccessTimeUtc {
      get { return lastAccessTimeUtc_; }
      set {
        lastAccessTimeUtc_ = value;
      }
    }

    /// <summary>Field number for the "LastWriteTimeUtc" field.</summary>
    public const int LastWriteTimeUtcFieldNumber = 10;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastWriteTimeUtc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastWriteTimeUtc {
      get { return lastWriteTimeUtc_; }
      set {
        lastWriteTimeUtc_ = value;
      }
    }

    /// <summary>Field number for the "Attributes" field.</summary>
    public const int AttributesFieldNumber = 11;
    private global::Image.FileAttributes attributes_ = global::Image.FileAttributes.FirstEnumValueToBeZeroInProto3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.FileAttributes Attributes {
      get { return attributes_; }
      set {
        attributes_ = value;
      }
    }

    /// <summary>Field number for the "ImageBlob" field.</summary>
    public const int ImageBlobFieldNumber = 12;
    private pb::ByteString imageBlob_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ImageBlob {
      get { return imageBlob_; }
      set {
        imageBlob_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Image);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Image other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Length != other.Length) return false;
      if (DirectoryName != other.DirectoryName) return false;
      if (IsReadOnly != other.IsReadOnly) return false;
      if (IsExists != other.IsExists) return false;
      if (FullName != other.FullName) return false;
      if (Extension != other.Extension) return false;
      if (!object.Equals(CreationTimeUtc, other.CreationTimeUtc)) return false;
      if (!object.Equals(LastAccessTimeUtc, other.LastAccessTimeUtc)) return false;
      if (!object.Equals(LastWriteTimeUtc, other.LastWriteTimeUtc)) return false;
      if (Attributes != other.Attributes) return false;
      if (ImageBlob != other.ImageBlob) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Length != 0L) hash ^= Length.GetHashCode();
      if (DirectoryName.Length != 0) hash ^= DirectoryName.GetHashCode();
      if (IsReadOnly != false) hash ^= IsReadOnly.GetHashCode();
      if (IsExists != false) hash ^= IsExists.GetHashCode();
      if (FullName.Length != 0) hash ^= FullName.GetHashCode();
      if (Extension.Length != 0) hash ^= Extension.GetHashCode();
      if (creationTimeUtc_ != null) hash ^= CreationTimeUtc.GetHashCode();
      if (lastAccessTimeUtc_ != null) hash ^= LastAccessTimeUtc.GetHashCode();
      if (lastWriteTimeUtc_ != null) hash ^= LastWriteTimeUtc.GetHashCode();
      if (Attributes != global::Image.FileAttributes.FirstEnumValueToBeZeroInProto3) hash ^= Attributes.GetHashCode();
      if (ImageBlob.Length != 0) hash ^= ImageBlob.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Length != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Length);
      }
      if (DirectoryName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DirectoryName);
      }
      if (IsReadOnly != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsReadOnly);
      }
      if (IsExists != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsExists);
      }
      if (FullName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FullName);
      }
      if (Extension.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Extension);
      }
      if (creationTimeUtc_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(CreationTimeUtc);
      }
      if (lastAccessTimeUtc_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(LastAccessTimeUtc);
      }
      if (lastWriteTimeUtc_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(LastWriteTimeUtc);
      }
      if (Attributes != global::Image.FileAttributes.FirstEnumValueToBeZeroInProto3) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Attributes);
      }
      if (ImageBlob.Length != 0) {
        output.WriteRawTag(98);
        output.WriteBytes(ImageBlob);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Length != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Length);
      }
      if (DirectoryName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DirectoryName);
      }
      if (IsReadOnly != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsReadOnly);
      }
      if (IsExists != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsExists);
      }
      if (FullName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FullName);
      }
      if (Extension.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Extension);
      }
      if (creationTimeUtc_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(CreationTimeUtc);
      }
      if (lastAccessTimeUtc_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(LastAccessTimeUtc);
      }
      if (lastWriteTimeUtc_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(LastWriteTimeUtc);
      }
      if (Attributes != global::Image.FileAttributes.FirstEnumValueToBeZeroInProto3) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Attributes);
      }
      if (ImageBlob.Length != 0) {
        output.WriteRawTag(98);
        output.WriteBytes(ImageBlob);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Length != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Length);
      }
      if (DirectoryName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DirectoryName);
      }
      if (IsReadOnly != false) {
        size += 1 + 1;
      }
      if (IsExists != false) {
        size += 1 + 1;
      }
      if (FullName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullName);
      }
      if (Extension.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Extension);
      }
      if (creationTimeUtc_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreationTimeUtc);
      }
      if (lastAccessTimeUtc_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastAccessTimeUtc);
      }
      if (lastWriteTimeUtc_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastWriteTimeUtc);
      }
      if (Attributes != global::Image.FileAttributes.FirstEnumValueToBeZeroInProto3) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Attributes);
      }
      if (ImageBlob.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ImageBlob);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Image other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Length != 0L) {
        Length = other.Length;
      }
      if (other.DirectoryName.Length != 0) {
        DirectoryName = other.DirectoryName;
      }
      if (other.IsReadOnly != false) {
        IsReadOnly = other.IsReadOnly;
      }
      if (other.IsExists != false) {
        IsExists = other.IsExists;
      }
      if (other.FullName.Length != 0) {
        FullName = other.FullName;
      }
      if (other.Extension.Length != 0) {
        Extension = other.Extension;
      }
      if (other.creationTimeUtc_ != null) {
        if (creationTimeUtc_ == null) {
          CreationTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreationTimeUtc.MergeFrom(other.CreationTimeUtc);
      }
      if (other.lastAccessTimeUtc_ != null) {
        if (lastAccessTimeUtc_ == null) {
          LastAccessTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastAccessTimeUtc.MergeFrom(other.LastAccessTimeUtc);
      }
      if (other.lastWriteTimeUtc_ != null) {
        if (lastWriteTimeUtc_ == null) {
          LastWriteTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastWriteTimeUtc.MergeFrom(other.LastWriteTimeUtc);
      }
      if (other.Attributes != global::Image.FileAttributes.FirstEnumValueToBeZeroInProto3) {
        Attributes = other.Attributes;
      }
      if (other.ImageBlob.Length != 0) {
        ImageBlob = other.ImageBlob;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Length = input.ReadInt64();
            break;
          }
          case 26: {
            DirectoryName = input.ReadString();
            break;
          }
          case 32: {
            IsReadOnly = input.ReadBool();
            break;
          }
          case 40: {
            IsExists = input.ReadBool();
            break;
          }
          case 50: {
            FullName = input.ReadString();
            break;
          }
          case 58: {
            Extension = input.ReadString();
            break;
          }
          case 66: {
            if (creationTimeUtc_ == null) {
              CreationTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreationTimeUtc);
            break;
          }
          case 74: {
            if (lastAccessTimeUtc_ == null) {
              LastAccessTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastAccessTimeUtc);
            break;
          }
          case 82: {
            if (lastWriteTimeUtc_ == null) {
              LastWriteTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastWriteTimeUtc);
            break;
          }
          case 88: {
            Attributes = (global::Image.FileAttributes) input.ReadEnum();
            break;
          }
          case 98: {
            ImageBlob = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Length = input.ReadInt64();
            break;
          }
          case 26: {
            DirectoryName = input.ReadString();
            break;
          }
          case 32: {
            IsReadOnly = input.ReadBool();
            break;
          }
          case 40: {
            IsExists = input.ReadBool();
            break;
          }
          case 50: {
            FullName = input.ReadString();
            break;
          }
          case 58: {
            Extension = input.ReadString();
            break;
          }
          case 66: {
            if (creationTimeUtc_ == null) {
              CreationTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreationTimeUtc);
            break;
          }
          case 74: {
            if (lastAccessTimeUtc_ == null) {
              LastAccessTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastAccessTimeUtc);
            break;
          }
          case 82: {
            if (lastWriteTimeUtc_ == null) {
              LastWriteTimeUtc = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastWriteTimeUtc);
            break;
          }
          case 88: {
            Attributes = (global::Image.FileAttributes) input.ReadEnum();
            break;
          }
          case 98: {
            ImageBlob = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ImageList : pb::IMessage<ImageList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageList> _parser = new pb::MessageParser<ImageList>(() => new ImageList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.ImageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageList(ImageList other) : this() {
      image_ = other.image_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageList Clone() {
      return new ImageList(this);
    }

    /// <summary>Field number for the "Image" field.</summary>
    public const int ImageFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Image.Image> _repeated_image_codec
        = pb::FieldCodec.ForMessage(10, global::Image.Image.Parser);
    private readonly pbc::RepeatedField<global::Image.Image> image_ = new pbc::RepeatedField<global::Image.Image>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Image.Image> Image {
      get { return image_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!image_.Equals(other.image_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= image_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      image_.WriteTo(output, _repeated_image_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      image_.WriteTo(ref output, _repeated_image_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += image_.CalculateSize(_repeated_image_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageList other) {
      if (other == null) {
        return;
      }
      image_.Add(other.image_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            image_.AddEntriesFrom(input, _repeated_image_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            image_.AddEntriesFrom(ref input, _repeated_image_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ImageRequest : pb::IMessage<ImageRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageRequest> _parser = new pb::MessageParser<ImageRequest>(() => new ImageRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.ImageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageRequest(ImageRequest other) : this() {
      filePath_ = other.filePath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageRequest Clone() {
      return new ImageRequest(this);
    }

    /// <summary>Field number for the "FilePath" field.</summary>
    public const int FilePathFieldNumber = 1;
    private string filePath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FilePath {
      get { return filePath_; }
      set {
        filePath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FilePath != other.FilePath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FilePath.Length != 0) hash ^= FilePath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FilePath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FilePath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FilePath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FilePath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FilePath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FilePath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageRequest other) {
      if (other == null) {
        return;
      }
      if (other.FilePath.Length != 0) {
        FilePath = other.FilePath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FilePath = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FilePath = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ImageResponse : pb::IMessage<ImageResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageResponse> _parser = new pb::MessageParser<ImageResponse>(() => new ImageResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.ImageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse(ImageResponse other) : this() {
      image_ = other.image_ != null ? other.image_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageResponse Clone() {
      return new ImageResponse(this);
    }

    /// <summary>Field number for the "Image" field.</summary>
    public const int ImageFieldNumber = 1;
    private global::Image.Image image_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.Image Image {
      get { return image_; }
      set {
        image_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Image, other.Image)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (image_ != null) hash ^= Image.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (image_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Image);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (image_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Image);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (image_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Image);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageResponse other) {
      if (other == null) {
        return;
      }
      if (other.image_ != null) {
        if (image_ == null) {
          Image = new global::Image.Image();
        }
        Image.MergeFrom(other.Image);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (image_ == null) {
              Image = new global::Image.Image();
            }
            input.ReadMessage(Image);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (image_ == null) {
              Image = new global::Image.Image();
            }
            input.ReadMessage(Image);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ImageListRequest : pb::IMessage<ImageListRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageListRequest> _parser = new pb::MessageParser<ImageListRequest>(() => new ImageListRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageListRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.ImageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageListRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageListRequest(ImageListRequest other) : this() {
      directoryPath_ = other.directoryPath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageListRequest Clone() {
      return new ImageListRequest(this);
    }

    /// <summary>Field number for the "DirectoryPath" field.</summary>
    public const int DirectoryPathFieldNumber = 1;
    private string directoryPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DirectoryPath {
      get { return directoryPath_; }
      set {
        directoryPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageListRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageListRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DirectoryPath != other.DirectoryPath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DirectoryPath.Length != 0) hash ^= DirectoryPath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DirectoryPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DirectoryPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DirectoryPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DirectoryPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DirectoryPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DirectoryPath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageListRequest other) {
      if (other == null) {
        return;
      }
      if (other.DirectoryPath.Length != 0) {
        DirectoryPath = other.DirectoryPath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DirectoryPath = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DirectoryPath = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ImageListResponse : pb::IMessage<ImageListResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImageListResponse> _parser = new pb::MessageParser<ImageListResponse>(() => new ImageListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImageListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Image.ImageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageListResponse(ImageListResponse other) : this() {
      imageList_ = other.imageList_ != null ? other.imageList_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImageListResponse Clone() {
      return new ImageListResponse(this);
    }

    /// <summary>Field number for the "ImageList" field.</summary>
    public const int ImageListFieldNumber = 1;
    private global::Image.ImageList imageList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Image.ImageList ImageList {
      get { return imageList_; }
      set {
        imageList_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImageListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImageListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ImageList, other.ImageList)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (imageList_ != null) hash ^= ImageList.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (imageList_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ImageList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (imageList_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ImageList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (imageList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ImageList);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImageListResponse other) {
      if (other == null) {
        return;
      }
      if (other.imageList_ != null) {
        if (imageList_ == null) {
          ImageList = new global::Image.ImageList();
        }
        ImageList.MergeFrom(other.ImageList);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (imageList_ == null) {
              ImageList = new global::Image.ImageList();
            }
            input.ReadMessage(ImageList);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (imageList_ == null) {
              ImageList = new global::Image.ImageList();
            }
            input.ReadMessage(ImageList);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
